[stdlib] Fix dict probing error
modular/modular pull request #2351
Opened 2024-04-20 08:57 UTC by mzaks

Fixes #1729

2024-04-23 19:27 UTC, bethebunny requested changes
Small style changes, looks great, thank you so much!

2024-04-23 19:27 UTC, bethebunny commented on stdlib/test/collections/test_dict.mojo
> +def test_probing_error():
can you rename this to `test_mojo_issue_1729`? that'll help point folks towards the issue context if/when someone trips this later

2024-04-24 16:53 UTC, bethebunny approved these changes

2024-04-26 16:51 UTC, ConnorGray commented
**✅🟣 This contribution has been merged 🟣✅**

Hi @mzaks thank you fixing this bug, great catch!

We're moving to a new infrastructure for merging contributions to Mojo (we're using a tool called [Copybara](https://github.com/google/copybara)), and your contribution has now been merged into our internal copy of the Mojo Standard Library.

The changes in this PR will appear here in the mojo repo `nightly` branch when we do our next outbound synchronization at the time that the next Mojo nightly is released. That should happen later today but could be delayed until Monday.

Thank you so much for the amazing catch 🔍  finding this bug and your 🔥 contribution fixing it :)

Please let me know if you have any questions or concerns.

2024-04-26 16:52 UTC, closed without merging