[stdlib] Add optional unwrap using `__getitem__ `
modular/modular pull request #3525
Opened 2024-09-22 21:00 UTC by martinvuyk

Add optional unwrap using `__getitem__ `

2024-09-22 21:09 UTC, helehex commented
Typically in the stdlib, `__getitem__()` returns a ref, not an owned value. I'm ok with this and might even prefer it, but we might want to consider if it's worth keeping it consistent throughout the stdlib, or where to break from it (maybe this is a case?)

2024-09-22 22:31 UTC, martinvuyk commented
Yeah I also think this breaks away from convention but in this case I think it makes sense since if you call a function and want to unwrap it doing `some_func()^` feels weird and `some_func()[][]` does not spark joy. Saying `some_func()[]` returns a reference that gets auto dereferenced also feels convoluted IMO. And logically speaking if you are unwrapping an Optional you most probably want to consume it taking ownership of the value not a reference of it :man_shrugging: . But honestly idc if it's a reference or a value as long as I can just do `some_func()[]` irresponsibly in raising functions, also no idea what kind of performance difference there might be.

2025-05-16 18:00 UTC, gryznar commented on stdlib/src/collections/optional.mojo
> +            raise Error("ValueError: take() on empty Optional")
To the stdlib team: Shall we have the same error system as Python has?
All ValueError, TypeError, etc? I am not sure if it is the greatest one

2025-05-16 18:05 UTC, gryznar commented on stdlib/src/collections/optional.mojo
> +            raise Error("ValueError: take() on empty Optional")
For me, only error message, without ValueError is informative on its own

2025-05-19 16:10 UTC, lsh requested changes

2025-05-19 16:10 UTC, lsh commented on stdlib/src/collections/optional.mojo
> +    fn __getitem__(owned self) raises -> T:
I would rather this not be consuming (i.e return `ref T`). If one needs to `take` the value, they can.

2025-05-19 16:35 UTC, martinvuyk commented on stdlib/src/collections/optional.mojo
> +    fn __getitem__(owned self) raises -> T:
True I think this was way back before we had `ref [_]`

2025-05-19 16:52 UTC, martinvuyk commented on stdlib/src/collections/optional.mojo
> +    fn __getitem__(owned self) raises -> T:
I also made it use `.value()` now because you're right that it might be best; just thinking about people using this the same as a pointer and referencing the value several times and it unexpectedly exploding in their faces is not the best

2025-05-19 17:02 UTC, lsh requested changes

2025-05-19 17:02 UTC, lsh commented on mojo/stdlib/stdlib/collections/optional.mojo
> +        return self.value()
I think this needs a branch and to raise if None

2025-05-19 17:03 UTC, martinvuyk commented on mojo/stdlib/stdlib/collections/optional.mojo
> +        return self.value()
yeah forgot about it

2025-05-19 17:27 UTC, lsh commented
!sync

2025-05-20 07:16 UTC, closed without merging